### ISSUE TITLE
Plan A or Plan B

### ISSUE THREAD

**Issue by nauticalmonkey** [nauticalmonkey/CalPolyThesis#2]
Brainstorm new ideas for Thesis that are fully remote.
for plan a reach out to dean about in person research on campus and dep head about funding for device (possible use of emotive in HCI course)

**Comment by nauticalmonkey** [comment]
Plan A

**Comment by bcdasilv** [comment]
Student work from 486: https://docs.google.com/document/d/17kqs6xOWLcdX1NgJyz4QN66-LNpHRAFIvkM6WvaCjhk/edit
and https://medium.com/@kelliebanzon/usability-study-of-web-browsers-via-analysis-of-brain-activity-7470dcaa06a6
There are others but those are the ones with a linked paper/article.

**Comment by bcdasilv** [comment]
Franz responded with these others 
https://docs.google.com/document/d/1zTbhscXpJJM4KQFV7ZipfxRwQECzC2v5bFN1ZjO5J-k/edit
https://docs.google.com/document/d/1ASbHCaJ4XeWMzuew80qFtUJvM6Dz6W-4xqTujTZ6-94/edit
https://drive.google.com/file/d/0B5fXoZHG7pskMHFMSDNqaWxXOWM/view
